# Generated by Django 3.1.3 on 2022-07-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
